FROM quay.io/rockylinux/rockylinux:9

ENV LOG_LEVEL=trace

RUN dnf update -y && dnf install -y fdo-admin-cli && dnf clean all

RUN mkdir -p /etc/fdo/keys

ENTRYPOINT ["/usr/libexec/fdo/fdo-admin-tool"]