FROM quay.io/rockylinux/rockylinux:9

ENV LOG_LEVEL=trace

RUN dnf update -y && dnf install -y fdo-rendezvous-server && dnf clean all

RUN mkdir -p /etc/fdo/rendezvous-server.conf.d
RUN mkdir -p /etc/fdo/stores/rendezvous_registered
RUN mkdir -p /etc/fdo/stores/rendezvous_sessions
RUN mkdir -p /etc/fdo/keys

RUN chmod -R 775 /etc/fdo

EXPOSE 8082
ENTRYPOINT ["/usr/libexec/fdo/fdo-rendezvous-server"]