FROM quay.io/rockylinux/rockylinux:9

ENV LOG_LEVEL=info

RUN dnf update -y && dnf install -y fdo-owner-cli && dnf clean all

RUN mkdir -p /etc/fdo
RUN chmod -R 775 /etc/fdo

ENTRYPOINT ["/usr/libexec/fdo/fdo-owner-tool"]