FROM quay.io/rockylinux/rockylinux:9

ENV LOG_LEVEL=trace

RUN dnf update -y && dnf install -y fdo-manufacturing-server && dnf clean all

RUN mkdir -p /etc/fdo/sessions
RUN mkdir -p /etc/fdo/manufacturing-server.conf.d
RUN mkdir -p /etc/fdo/ownership_vouchers
RUN mkdir -p /etc/fdo/keys

RUN chmod -R 775 /etc/fdo

EXPOSE 8080
ENTRYPOINT ["/usr/libexec/fdo/fdo-manufacturing-server"]