---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdomanufacturingservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdomanufacturingservers/finalizers
  verbs:
  - update
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdomanufacturingservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdoonboardingservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdoonboardingservers/finalizers
  verbs:
  - update
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdoonboardingservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdorendezvousservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdorendezvousservers/finalizers
  verbs:
  - update
- apiGroups:
  - fdo.redhat.com
  resources:
  - fdorendezvousservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
