apiVersion: fdo.redhat.com/v1alpha1
kind: FDOOnboardingServer
metadata:
  name: onboarding-server
spec:
  ownerOnboardingImage: quay.io/vemporop/fdo-owner-onboarding-server:rhel9.3
  serviceInfoImage: quay.io/vemporop/fdo-serviceinfo-api-server:rhel9.3
  serviceInfo:
    commands:
      - command: /bin/sh
        args:
          - /var/tmp/msg-to-file.sh
          - This device has been onboarded by FDO
          - /var/tmp/fdo_message.txt
        mayFail: false
        returnStdOut: true
        returnStdErr: true
