apiVersion: fdo.redhat.com/v1alpha1
kind: FDOOnboardingServer
metadata:
  name: onboarding-server
spec:
  ownerOnboardingImage: quay.io/fido-fdo/owner-onboarding-server:0.4
  serviceInfoImage: quay.io/fido-fdo/serviceinfo-api-server:0.4
  serviceInfo:
    commands:
      - command: /bin/sh
        args:
          - /var/tmp/msg-to-file.sh
          - This device has been onboarded by FDO
          - /var/tmp/fdo_message.txt
        mayFail: false
        returnStdOut: true
        returnStdErr: true
    initialUser:
        username: admin
        password: admin
