//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DIUN) DeepCopyInto(out *DIUN) {
	*out = *in
	if in.AllowedKeyStorageTypes != nil {
		in, out := &in.AllowedKeyStorageTypes, &out.AllowedKeyStorageTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DIUN.
func (in *DIUN) DeepCopy() *DIUN {
	if in == nil {
		return nil
	}
	out := new(DIUN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FDOManufacturingServer) DeepCopyInto(out *FDOManufacturingServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FDOManufacturingServer.
func (in *FDOManufacturingServer) DeepCopy() *FDOManufacturingServer {
	if in == nil {
		return nil
	}
	out := new(FDOManufacturingServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FDOManufacturingServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FDOManufacturingServerList) DeepCopyInto(out *FDOManufacturingServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FDOManufacturingServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FDOManufacturingServerList.
func (in *FDOManufacturingServerList) DeepCopy() *FDOManufacturingServerList {
	if in == nil {
		return nil
	}
	out := new(FDOManufacturingServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FDOManufacturingServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FDOManufacturingServerSpec) DeepCopyInto(out *FDOManufacturingServerSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.RendezvousServers != nil {
		in, out := &in.RendezvousServers, &out.RendezvousServers
		*out = make([]RendezvousServer, len(*in))
		copy(*out, *in)
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = new(Protocols)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FDOManufacturingServerSpec.
func (in *FDOManufacturingServerSpec) DeepCopy() *FDOManufacturingServerSpec {
	if in == nil {
		return nil
	}
	out := new(FDOManufacturingServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FDOManufacturingServerStatus) DeepCopyInto(out *FDOManufacturingServerStatus) {
	*out = *in
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FDOManufacturingServerStatus.
func (in *FDOManufacturingServerStatus) DeepCopy() *FDOManufacturingServerStatus {
	if in == nil {
		return nil
	}
	out := new(FDOManufacturingServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Protocols) DeepCopyInto(out *Protocols) {
	*out = *in
	if in.DIUN != nil {
		in, out := &in.DIUN, &out.DIUN
		*out = new(DIUN)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Protocols.
func (in *Protocols) DeepCopy() *Protocols {
	if in == nil {
		return nil
	}
	out := new(Protocols)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RendezvousServer) DeepCopyInto(out *RendezvousServer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RendezvousServer.
func (in *RendezvousServer) DeepCopy() *RendezvousServer {
	if in == nil {
		return nil
	}
	out := new(RendezvousServer)
	in.DeepCopyInto(out)
	return out
}
